services:
  tickets-backend:
    image: lobanovsky/tickets-backend:${TAG}
    container_name: tickets-backend
    restart: always
    environment:
      TZ: Europe/Moscow
      # database credentials
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # api keys
      VAKHTANGOV_API_KEY: ${VAKHTANGOV_API_KEY}
      RAMT_API_KEY: ${RAMT_API_KEY}
      NATIONS_API_KEY: ${NATIONS_API_KEY}
      FOMENKI_API_KEY: ${FOMENKI_API_KEY}
      LENSOV_API_KEY: ${LENSOV_API_KEY}
      MXT_API_KEY: ${MXT_API_KEY}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      # telegram bot token
      BOT_TOKEN_VAKHTANGOV: ${BOT_TOKEN_VAKHTANGOV}
      BOT_TOKEN_RAMT: ${BOT_TOKEN_RAMT}
      BOT_TOKEN_NATIONS: ${BOT_TOKEN_NATIONS}
      BOT_TOKEN_FOMENKI: ${BOT_TOKEN_FOMENKI}
      BOT_TOKEN_LENSOV: ${BOT_TOKEN_LENSOV}
      BOT_TOKEN_MXT: ${BOT_TOKEN_MXT}
      # webhooks
      BOT_WEBHOOK_URL_VAKHTANGOV: ${BOT_WEBHOOK_URL_VAKHTANGOV}
      BOT_WEBHOOK_SECRET_VAKHTANGOV: ${BOT_WEBHOOK_SECRET_VAKHTANGOV}
      BOT_WEBHOOK_URL_FOMENKI: ${BOT_WEBHOOK_URL_FOMENKI}
      BOT_WEBHOOK_SECRET_FOMENKI: ${BOT_WEBHOOK_SECRET_FOMENKI}
      BOT_WEBHOOK_URL_NATIONS: ${BOT_WEBHOOK_URL_NATIONS}
      BOT_WEBHOOK_SECRET_NATIONS: ${BOT_WEBHOOK_SECRET_NATIONS}
      BOT_WEBHOOK_URL_RAMT: ${BOT_WEBHOOK_URL_RAMT}
      BOT_WEBHOOK_SECRET_RAMT: ${BOT_WEBHOOK_SECRET_RAMT}
      BOT_WEBHOOK_URL_LENSOV: ${BOT_WEBHOOK_URL_LENSOV}
      BOT_WEBHOOK_SECRET_LENSOV: ${BOT_WEBHOOK_SECRET_LENSOV}
      BOT_WEBHOOK_URL_MXT: ${BOT_WEBHOOK_URL_MXT}
      BOT_WEBHOOK_SECRET_MXT: ${BOT_WEBHOOK_SECRET_MXT}
      # telegram-api-key
      TELEGRAM_API_URL: ${TELEGRAM_API_URL}
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8078:8080"
    env_file:
      - .env
    networks:
        - tickets-network

networks:
    tickets-network:
        external: true