ktor:
  application:
    modules:
      - ru.tickets.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: ${DB_URL:jdbc:postgresql://localhost:5455/tickets}
  user: ${DB_USER:tickets}
  password: ${DB_PASSWORD:tickets}

bot-webhooks:
  vakhtangov:
    url: ${BOT_WEBHOOK_URL_VAKHTANGOV:}
    secret: ${BOT_WEBHOOK_SECRET_VAKHTANGOV:}
  ramt:
    url: ${BOT_WEBHOOK_URL_RAMT:}
    secret: ${BOT_WEBHOOK_SECRET_RAMT:}
  nations:
    url: ${BOT_WEBHOOK_URL_NATIONS:}
    secret: ${BOT_WEBHOOK_SECRET_NATIONS:}
  fomenki:
    url: ${BOT_WEBHOOK_URL_FOMENKI:}
    secret: ${BOT_WEBHOOK_SECRET_FOMENKI:}
  lensov:
    url: ${BOT_WEBHOOK_URL_LENSOV:}
    secret: ${BOT_WEBHOOK_SECRET_LENSOV:}
  mxt:
    url: ${BOT_WEBHOOK_URL_MXT:}
    secret: ${BOT_WEBHOOK_SECRET_MXT:}
  satirikon:
    url: ${BOT_WEBHOOK_URL_SATIRIKON:}
    secret: ${BOT_WEBHOOK_SECRET_SATIRIKON:}

bot-tokens:
  vakhtangov: ${BOT_TOKEN_VAKHTANGOV:}
  ramt: ${BOT_TOKEN_RAMT:}
  nations: ${BOT_TOKEN_NATIONS:}
  fomenki: ${BOT_TOKEN_FOMENKI:}
  lensov: ${BOT_TOKEN_LENSOV:}
  mxt: ${BOT_TOKEN_MXT:}
  satirikon: ${BOT_TOKEN_SATIRIKON:}

telegram-api:
  url: ${TELEGRAM_API_URL:http://localhost:8080}
  key: ${TELEGRAM_API_KEY:telegram-api}

api-keys:
  ramt: ${RAMT_API_KEY:ramt-secret}
  nations: ${NATIONS_API_KEY:nations-secret}
  vakhtangov: ${VAKHTANGOV_API_KEY:vakhtangov-secret}
  fomenki: ${FOMENKI_API_KEY:fomenki-secret}
  lensov: ${LENSOV_API_KEY:lensov-secret}
  mxt: ${MXT_API_KEY:mxt-secret}
  satirikon: ${SATIRIKON_API_KEY:satirikon-secret}
  admin: ${ADMIN_API_KEY:admin-secret}
