ktor:
  application:
    modules:
      - ru.tickets.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: ${DB_URL:jdbc:postgresql://localhost:5455/tickets}
  user: ${DB_USER:tickets}
  password: ${DB_PASSWORD:tickets}

api-keys:
  ramt: ${RAMT_API_KEY:ramt-secret}
  nations: ${NATIONS_API_KEY:nations-secret}
  vakhtangov: ${VAKHTANGOV_API_KEY:vakhtangov-secret}
  fomenki: ${FOMENKI_API_KEY:fomenki-secret}
  admin: ${ADMIN_API_KEY:admin-secret}
