ktor:
  application:
    modules:
      - ru.tickets.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: ${DB_URL:jdbc:postgresql://localhost:5455/tickets}
  user: ${DB_USER:tickets}
  password: ${DB_PASSWORD:tickets}

bot-webhooks:
  vakhtangov:
    url: ${BOT_WEBHOOK_URL_VAKHTANGOV:}
    secret: ${BOT_WEBHOOK_SECRET_VAKHTANGOV:}
  ramt:
    url: ${BOT_WEBHOOK_URL_RAMT:}
    secret: ${BOT_WEBHOOK_SECRET_RAMT:}
  nations:
    url: ${BOT_WEBHOOK_URL_NATIONS:}
    secret: ${BOT_WEBHOOK_SECRET_NATIONS:}
  fomenki:
    url: ${BOT_WEBHOOK_URL_FOMENKI:}
    secret: ${BOT_WEBHOOK_SECRET_FOMENKI:}
  lensov:
    url: ${BOT_WEBHOOK_URL_LENSOV:}
    secret: ${BOT_WEBHOOK_SECRET_LENSOV:}

api-keys:
  ramt: ${RAMT_API_KEY:ramt-secret}
  nations: ${NATIONS_API_KEY:nations-secret}
  vakhtangov: ${VAKHTANGOV_API_KEY:vakhtangov-secret}
  fomenki: ${FOMENKI_API_KEY:fomenki-secret}
  lensov: ${LENSOV_API_KEY:lensov-secret}
  admin: ${ADMIN_API_KEY:admin-secret}
